<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.8" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.*" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.*" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
    <PackageReference Include="Tesseract" Version="5.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.12" />

  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="DownloadTessdata" BeforeTargets="Build">
    <PropertyGroup>
      <TessdataDir>$(ProjectDir)tessdata</TessdataDir>
      <TessdataFile>$(TessdataDir)\eng.traineddata</TessdataFile>
    </PropertyGroup>
    <MakeDir Directories="$(TessdataDir)" Condition="!Exists('$(TessdataDir)')" />
    <Exec Command="powershell -Command &quot;Invoke-WebRequest -Uri 'https://github.com/tesseract-ocr/tessdata_fast/raw/main/eng.traineddata' -OutFile '$(TessdataFile)'&quot;" Condition="!Exists('$(TessdataFile)')" />
  </Target>

</Project>
